networks:
  Mine:
    external: true
  PyPikachu:
    name: PyPikachu

services:
  pidgeotto:
    image: heisodin/pidgeotto:latest
    container_name: Pidgeotto
    environment:
      POSTGRESQL_TABLE_FOR_TASKS: ${POSTGRESQL_TABLE_FOR_TASKS}
      POSTGRESQL_TABLE_FOR_USERS: ${POSTGRESQL_TABLE_FOR_USERS}
      POSTGRESQL_TABLE_FOR_REPORTS: ${POSTGRESQL_TABLE_FOR_REPORTS}
      POSTGRESQL_DBNAME: ${POSTGRESQL_DBNAME}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWD: ${POSTGRESQL_PASSWD}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-localhost}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT:-5432}
      EMAIL: ${EMAIL}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_BASE_URL: ${MAILGUN_BASE_URL}
    networks:
      - PyPikachu
      - Mine
    restart: unless-stopped

  celebi:
    image: heisodin/celebi:latest
    container_name: Celebi
    environment:
      POSTGRESQL_TABLE_FOR_TASKS: ${POSTGRESQL_TABLE_FOR_TASKS}
      POSTGRESQL_TABLE_FOR_REPORTS: ${POSTGRESQL_TABLE_FOR_REPORTS}
      POSTGRESQL_DBNAME: ${POSTGRESQL_DBNAME}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWD: ${POSTGRESQL_PASSWD}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-localhost}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT:-5432}
      EBAY_CLIENT_ID: ${EBAY_CLIENT_ID}
      EBAY_CLIENT_SECRET: ${EBAY_CLIENT_SECRET}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      KAGGLE_CRED_DIR: ${KAGGLE_CRED_DIR}
      DATASETS_DIR: ${DATASETS_DIR}
    networks:
      - PyPikachu
      - Mine
    restart: unless-stopped

  zapdos:
    image: heisodin/zapdos:latest
    container_name: Zapdos
    environment:
      POSTGRESQL_TABLE_FOR_TASKS: ${POSTGRESQL_TABLE_FOR_TASKS}
      POSTGRESQL_TABLE_FOR_USERS: ${POSTGRESQL_TABLE_FOR_USERS}
      POSTGRESQL_DBNAME: ${POSTGRESQL_DBNAME}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWD: ${POSTGRESQL_PASSWD}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-localhost}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT:-5432}
      FLASK_PORT: ${FLASK_PORT:-5000}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    networks:
      - PyPikachu
      - Mine
    restart: unless-stopped